spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 2000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# Spring 将会通过如下的配置初始化一个至关重要的 OAuth2ClientContext 对象
security:
  oauth2:
    # 想要 token relay，首先，该微服务 order-service 必须是一个合法的 client，才能进行 token relay
    client:
      client-id: inner
      client-secret: inner
    resource:
      token-info-uri: http://localhost:8000/uaa/oauth/check_token

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  SocketTimeout: 3000
  ReadTimeout: 60000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG 
    org.shangyang.springcloud: DEBUG