spring:
  application:
    name: order-service
    
server:
  port: 2000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
security:
  oauth2:
    # 想要 token relay，首先，该微服务 order-service 必须是一个合法的 client，才能进行 token relay
    client:
      client-id: inner
      client-secret: inner
    resource:
      token-info-uri: http://localhost:8000/uaa/oauth/check_token

hystrix.shareSecurityContext: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG 
    org.shangyang.springcloud: DEBUG