spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      registerWithEureka: false
      fetchRegistry: true

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth:
      path: /uaa/**
      serviceId: auth-service
      stripPrefix: false
    order:
      path: /order/**
      serviceId: order-service
      stripPrefix: false
    stock:
      path: /stock/**
      serviceId: stock-service
      stripPrefix: false

# Gateway 容易 timeout，增加 timeout 的时限；
# https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.1.0.RELEASE/single/spring-cloud-netflix.html#_zuul_timeouts
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  SocketTimeout: 3000
  ReadTimeout: 60000

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG