spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/myoauth
    username: root
    password:
  # org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'dataSource'
  # defined in BeanDefinition defined in class path resource
  # [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]
  # 导致上面这个错误的原因是，是因为从 Spring Boot 2.1.x 开始取消了重载 bean definitions 的的特性，使用下面这个配置重新开启它；
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

security:
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()
    resource:
      user-info-uri: /user
      
server:
  port: 9999
  servlet:
    context-path: /uaa
  
logging:
  level:
    org.springframework.security: DEBUG